CREATE TABLE categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  parent_id UUID REFERENCES categories(id)
    ON DELETE RESTRICT,

  name VARCHAR(100) NOT NULL,

  slug VARCHAR(120) NOT NULL UNIQUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);